# Generated by Django 3.1.5 on 2021-01-11 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auto_20210111_1916'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auctionlisting',
            old_name='category_id',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='auctionlisting',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='bid',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='listing_id',
            new_name='listing',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='watchlist',
            old_name='listing_id',
            new_name='listing',
        ),
        migrations.RenameField(
            model_name='watchlist',
            old_name='user_id',
            new_name='user',
        ),
    ]
