# Generated by Django 3.1.5 on 2021-01-15 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_auto_20210115_1238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlisting',
            name='cur_bid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='current_bid', to='auctions.bid'),
        ),
    ]
