# Generated by Django 3.1.5 on 2021-01-19 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_auctionlisting_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auctionlisting',
            name='watchers',
        ),
        migrations.AddField(
            model_name='auctionlisting',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='watchlist',
            field=models.ManyToManyField(blank=True, related_name='watchers', to='auctions.AuctionListing'),
        ),
    ]
