# Generated by Django 3.1.5 on 2021-02-25 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0012_auto_20210202_1907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item_category',
            name='name',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
