# Generated by Django 3.1.5 on 2021-02-25 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0013_auto_20210225_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item_category',
            name='name',
            field=models.CharField(max_length=32),
        ),
    ]
